services:
  lb:
    image: ${LB_IMAGE:-ghcr.io/fksegundo/rinha-api-lb:latest}
    pull_policy: always
    cpuset: "2,3"
    user: "0:0"
    security_opt:
      - seccomp=unconfined
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    volumes:
      - sockets:/sockets
    environment:
      PORT: "9999"
      UPSTREAMS: "/sockets/api1.sock,/sockets/api2.sock"
      WORKERS: "2"
    deploy:
      resources:
        limits:
          cpus: "${LB_CPUS:-0.10}"
          memory: "30MB"
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
  api1:
    image: ${APP_IMAGE:-ghcr.io/fksegundo/rinha-api:latest}
    pull_policy: always
    cpuset: "0"
    restart: always
    user: "0:0"
    security_opt:
      - seccomp=unconfined
    environment:
      DOTNET_PROCESSOR_COUNT: "1"
      DOTNET_GCHeapCount: "1"
      RINHA_SEARCH_BACKEND: ${RINHA_SEARCH_BACKEND:-rust}
      RINHA_SOCKET: /sockets/api1.sock
      RINHA_NATIVE_INDEX_PATH: /app/index/native.idx
      DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: "1"
      DOTNET_GCConserveMemory: "9"
      DOTNET_GCHeapHardLimit: "134217728"
    volumes:
      - sockets:/sockets
    deploy:
      resources:
        limits:
          cpus: "${API1_CPUS:-0.45}"
          memory: "160MB"

  api2:
    image: ${APP_IMAGE:-ghcr.io/fksegundo/rinha-api:latest}
    pull_policy: always
    cpuset: "1"
    restart: always
    user: "0:0"
    security_opt:
      - seccomp=unconfined
    environment:
      DOTNET_PROCESSOR_COUNT: "1"
      DOTNET_GCHeapCount: "1"
      RINHA_SEARCH_BACKEND: ${RINHA_SEARCH_BACKEND:-rust}
      RINHA_SOCKET: /sockets/api2.sock
      RINHA_NATIVE_INDEX_PATH: /app/index/native.idx
      DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: "1"
      DOTNET_GCConserveMemory: "9"
      DOTNET_GCHeapHardLimit: "125829120"
    volumes:
      - sockets:/sockets
    deploy:
      resources:
        limits:
          cpus: "${API2_CPUS:-0.45}"
          memory: "160MB"

volumes:
  sockets:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: "size=4m,mode=0777"
