services:
  lb:
    image: ${LB_IMAGE:-filonsegundo/rinha-dotnetrust-lb:submission}
    pull_policy: always
    cpuset: "2,3"
    security_opt:
      - seccomp=unconfined
    depends_on:
      - api1
      - api2
    environment:
      UPSTREAMS: /sockets/api1.sock,/sockets/api2.sock
      PORT: "9999"
      BUF_SIZE: ${LB_BUF_SIZE:-4096}
      WORKERS: ${LB_WORKERS:-1}
    ports:
      - "9999:9999"
    volumes:
      - sockets:/sockets
    deploy:
      resources:
        limits:
          cpus: "${LB_CPUS:-0.20}"
          memory: "40MB"
    ulimits:
      nofile:
        soft: 65535
        hard: 65535

  api1:
    image: ${APP_IMAGE:-filonsegundo/rinha-dotnetrust-api:v0.3}
    pull_policy: always
    cpuset: "0"
    restart: always
    user: "0:0"
    environment:
      DOTNET_PROCESSOR_COUNT: "1"
      DOTNET_GCHeapCount: "1"
      RINHA_SEARCH_BACKEND: ${RINHA_SEARCH_BACKEND:-rust}
      RINHA_SOCKET: /sockets/api1.sock
      RINHA_INDEX_PATH: /app/index/rinha.idx
      RINHA_NATIVE_INDEX_PATH: /app/index/native.idx
      RINHA_PROBES: ${RINHA_PROBES:-2}
      RINHA_MAX_CANDIDATES_PER_CENTER: ${RINHA_MAX_CANDIDATES_PER_CENTER:-768}
      RINHA_NATIVE_FAST_PROBES: ${RINHA_NATIVE_FAST_PROBES:-16}
      RINHA_NATIVE_FULL_PROBES: ${RINHA_NATIVE_FULL_PROBES:-64}
      DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: "1"
    volumes:
      - sockets:/sockets
    deploy:
      resources:
        limits:
          cpus: "${API1_CPUS:-0.40}"
          memory: "155MB"

  api2:
    image: ${APP_IMAGE:-filonsegundo/rinha-dotnetrust-api:v0.3}
    pull_policy: always
    cpuset: "1"
    restart: always
    user: "0:0"
    environment:
      DOTNET_PROCESSOR_COUNT: "1"
      DOTNET_GCHeapCount: "1"
      RINHA_SEARCH_BACKEND: ${RINHA_SEARCH_BACKEND:-rust}
      RINHA_SOCKET: /sockets/api2.sock
      RINHA_INDEX_PATH: /app/index/rinha.idx
      RINHA_NATIVE_INDEX_PATH: /app/index/native.idx
      RINHA_PROBES: ${RINHA_PROBES:-2}
      RINHA_MAX_CANDIDATES_PER_CENTER: ${RINHA_MAX_CANDIDATES_PER_CENTER:-768}
      RINHA_NATIVE_FAST_PROBES: ${RINHA_NATIVE_FAST_PROBES:-16}
      RINHA_NATIVE_FULL_PROBES: ${RINHA_NATIVE_FULL_PROBES:-64}
      DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: "1"
    volumes:
      - sockets:/sockets
    deploy:
      resources:
        limits:
          cpus: "${API2_CPUS:-0.40}"
          memory: "155MB"

volumes:
  sockets:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: "size=4m,mode=0777"
