services:
  lb:
    cpuset: "${LB_CPUSET:-0}"

  api1:
    cpuset: "${API1_CPUSET:-1}"
    environment:
      RINHA_MIN_THREADS: "${RINHA_MIN_THREADS:-}"

  api2:
    cpuset: "${API2_CPUSET:-2}"
    environment:
      RINHA_MIN_THREADS: "${RINHA_MIN_THREADS:-}"
